### ISSUE TITLE
Bar charts no longer stacked with apex-charts v2.1.2

### ISSUE THREAD

**Issue by purcell-lab** [melvanderwal/HA-Amber-Electric-Usage-Charts#3]
With the update to apex-charts v2.1.2, I find the bar charts are no longer on top of each other;

v2.1.2

![image](https://github.com/user-attachments/assets/6014cb6b-dbbc-4259-9e77-ab547195babe)

Older version:

![image](https://github.com/user-attachments/assets/961c365e-9aa5-4327-8d6c-7845390eef93)

Any ideas how we can configure v2.1.2 to present the old style stack charts?

**Comment by melvanderwal** [comment]
Hi Mark.

Thanks for the example, I see what you mean. I'm travelling overseas for another week and I won't be able to look at it until I return, but I will do so.

**Comment by melvanderwal** [comment]
Hi @purcell-lab.

It's a simple fix.  At Apex Charts 2.1, the series `stack_group` property was introduced.   Just group your series using a common group name, for example:
![image](https://github.com/user-attachments/assets/84af2b5e-a062-49a4-ab33-a6c4099226ab)

I'll add it to the code in the repo.

**Comment by melvanderwal** [comment]
`stack_group` added to example Apex Charts YAML file.
